name: dotnet format
on:
  push:
    branches: [develop]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Run dotnet format
        id: format
        uses: jfversluis/dotnet-format@v1.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          workspace: "./src/CSharp/EasyMicroservices.Serialization-net6.0.sln"
      - name: Test
        run: dotnet test ./src/CSharp/EasyMicroservices.Serialization-net6.0.sln
      - name:  Test to generate Code Coverage Report
        working-directory: ./src/CSharp
        run: |
          dotnet build ./EasyMicroservices.Serialization-net6.0.sln
          dotnet tool install --global coverlet.console
          coverlet EasyMicroservices.Serialization.Tests/bin/Debug/net6.0/EasyMicroservices.Serialization.Tests.dll --target "dotnet" --targetargs "test EasyMicroservices.Serialization.Tests/bin/Debug/net6.0/EasyMicroservices.Serialization.Tests.dll --no-build" -f opencover
      - name: OpenCover Badge Generator
        uses: danpetitt/open-cover-badge-generator-action@v1.0.9
        with:
          path-to-opencover-xml: ./src/CSharp/coverage.opencover.xml
          path-to-badges: ./src/CSharp
          minimum-coverage: 50
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        uses: EndBug/add-and-commit@v4.1.0
        with:
          author_name: Github Actions
          author_email: actions@github.com
          message: "chore: Automated dotnet-format update"
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
