name: MacOS (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.Serialization.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.Serialization.sln --no-restore
      - name: Test
        run: dotnet test ./src/CSharp/EasyMicroservices.Serialization.sln --no-build --verbosity diag
